
platform:

  - x64



environment:

  GENERATOR: "Visual Studio 14 2015 Win64"

  CONFIG: Debug

  BOOST_ROOT: "C:\\Libraries\\boost_1_59_0"

  BOOST_LIBRARYDIR: "C:\\Libraries\\boost_1_59_0\\lib64-msvc-14.0"

  PATH: "%BOOST_LIBRARYDIR%;%PATH%"



build_script:

  - echo "%PATH%"

  - mkdir build

  - cd build

  - cmake -G "%GENERATOR%" -DCMAKE_BUILD_TYPE="%CONFIG%" -DBOOST_ROOT="%BOOST_ROOT%" -DBOOST_LIBRARYDIR="%BOOST_LIBRARYDIR%" ..

  - cmake --build . --config "%CONFIG%"



test_script:

  - cmake --build . --target check --config "%CONFIG%"